fix(ui): don't add `blockType: undefined` with row
Fixes that when adding new array rows, the row was assigned
`blockType: undefined`.

This caused `POST /admin/collections/$myCollection/create` and
`/admin/collections/$myCollection/update` API calls to send `$undefined`
as `blockType`, which for some collections caused the following
response as soon as a 2nd row would be added:

```
ERROR: There was an error building form state
    err: {
      "type": "Error",
      "message": "Block with type \"undefined\" was found in block data, but no block with that type is defined in the config for field with schema path $myCollection.$myArrayField",
```

The request would receive this error, which is unfortunately swallowed
and not indicated to the user, except that the new row would
indefinitely be stuck in the loading state.

However, if a user saved a draft with an array field with 2 rows with
`blockType: '$undefined'`, opening the document wasn't possible anymore,
because even the GET requets to open the document would throw this error
as internal server error, and the front end show an empty area in place
of the document editing form, again without any error indication.

There's probably a better place to filter out `'$undefined'` properties
before sending them off in
`POST /admin/collections/$myCollection/create` and `update`, and
`addFieldStatePromises.ts` could graciously ignore blocks with
`blockType: $undefined` instead of throwing the error. But this change
is minimal and appears to do the trick.