fix(plugin-import-export): errors when import/export files were stored in a storage adapter such as S3 (#15441)
Relies on https://github.com/payloadcms/payload/pull/15405 first

When using a storage adapter such as S3 to handle files there were
errors in the way the files would be fetched for imports.

This PR fixes that, adding test coverage and changes the job behaviour
so that it only stores the import doc ID and not the full file data -
this avoids many problems down the line and optimises memory and storage
usage.

Fixes https://github.com/payloadcms/payload/issues/15247

Previously attempting to use an import with the jobs queue with S3
storage would result in this error:

```text
[11:46:25] ERROR: Failed to queue import job for document 698628f19aaca7d4f4f18c6e
    err: {
      "type": "Error",
      "message": "ENOENT: no such file or directory, open '/posts-with-s3-import/2026-02-06 114542.csv'",
      "stack":
          Error: ENOENT: no such file or directory, open '/posts-with-s3-import/2026-02-06 114542.csv'
```

Also:
- Exports `getExternalFile` utility from `payload/internals`